server:
  port: 8088
  servlet:
    context-path: /demo

spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /statics/**
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:33062/demo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: measurement
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
logging:
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      file-name-pattern: logs/demo.%d{yyyy-MM-dd}.%i.log
  file:
    name: logs/demo.log